baseURL: "https://covid19uy.com/"
languageCode: "es-UY"
DefaultContentLanguage: es
enableRobotsTXT: true
googleAnalytics: UA-161714981-1

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true
  twitter:
    enableDNT: true

disableKinds:
  - page
  - taxonomy
  - taxonomyTerm

outputs:
  home:
    - HTML

params:
  kofi: false
  share:
    - name: Facebook
      icon: fab fa-facebook
      url: https://facebook.com/sharer/sharer.php?u=$url
      target: _blank
    - name: Twitter
      icon: fab fa-twitter
      url: https://twitter.com/intent/tweet/?text=$title&url=$url
      target: _blank
    - name: E-Mail
      icon: fas fa-envelope
      url: mailto:?subject=$title&body=$url
      target: _self
    - name: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/shareArticle?mini=true&url=$url&title=$title&summary=$title&source=$url
      target: _blank
    - name: Reddit
      icon: fab fa-reddit
      url: https://reddit.com/submit/?url=$url&resubmit=true&title=$title
      target: _blank
    - name: WhatsApp
      icon: fab fa-whatsapp
      url: whatsapp://send?text=$title%20$url
      target: _blank

languages:
  es:
    languageName: Español
    weight: 1
    title: "Coronavirus COVID-19 en Uruguay | #QuedateEnCasa"
    params:
      schemaName: Spanish
      numberFormat: "- , ."
      dateFormat: "02/01/2006 15:04:05"
      dateFormatCompact: "02/01/2006"
  en:
    languageName: English
    weight: 2
    title: "Coronavirus COVID-19 in Uruguay | #StayHome"
    params:
      schemaName: English
      numberFormat: "- . ,"
      dateFormat: "01/02/2006 03:04:05 PM"
      dateFormatCompact: "01/02/2006"