baseURL: "https://covid19uy.com/"
languageCode: "es-UY"
DefaultContentLanguage: es-UY
title: "Coronavirus COVID-19 en Uruguay"
enableRobotsTXT: true
googleAnalytics: UA-161714981-1

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true

disableKinds:
  - page
  - section
  - taxonomy
  - taxonomyTerm

outputs:
  home:
    - HTML
