[context.deploy-preview.environment]
  HUGO_VERSION = "0.68.3"

[context.production.environment]
  HUGO_VERSION = "0.68.3"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.68.3"

[build]
publish = "public"
command = "gulp deploy"

[build.environment]
  TZ = "America/Montevideo"

[[redirects]]
from = "https://coronavirusuy.netlify.com/*"
to = "https://covid19uy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://covid19uy.netlify.com/*"
to = "https://covid19uy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://coronavirusuy.netlify.app/*"
to = "https://covid19uy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://covid19uy.netlify.app/*"
to = "https://covid19uy.com/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/en/:splat"
status = 302
conditions = {Language = ["en"]}
force = false

[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 302
force = false