[context.deploy-preview.environment]
  HUGO_VERSION = "0.68.3"

[context.production.environment]
  HUGO_VERSION = "0.68.3"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.68.3"

[build]
publish = "public"
command = "gulp deploy"

[build.environment]
  TZ = "America/Montevideo"

[[redirects]]
from = "https://coronavirusuy.netlify.com/*"
to = "https://covid19uy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://covid19uy.netlify.com/*"
to = "https://covid19uy.com/:splat"
status = 301
force = true